### ISSUE TITLE
Things not working

### ISSUE THREAD

**Issue by Zhanytrix** [carbon-language/carbon-lang#1614] opened 2022-07-23 13:19 UTC
Hi I found other things not working as the documentation says:
For example;
```for (var name: String in names)``` will give ```unexpected VAR```. If I remove it ```for (name: String in names)``` it will give ```unexpected COLON```
```Console.Print()``` in any case will give me ```syntax error, unexpected intrinsic_identifier, expecting identifier or LEFT_PARENTHESIS```
I cannot do things like ```i += 1``` (like the documentation says) it will give me ```syntax error, unexpected EQUAL```

#1590

**Comment by jonmeow** [comment] 2022-07-23 15:51
Duplicate of #1592

**Closed as completed by jonmeow** 2022-07-23 15:51 UTC
