### ISSUE TITLE
Down with declaration order in packages

### ISSUE THREAD

**Issue by DaemonSnake** [carbon-language/carbon-lang#1741] opened 2022-07-26 13:57 UTC
Hi

One of the things I enjoyed in Dlang's take on C++ was that the declaration order was is in effect eradicated.
This means that we don't have to forward declare, separate definitions from declarations, etc.
Most modern languages behave that way (Rust, Go, Dlang, etc.).

I can sum up the issue with this example:
```golang
package sample api;

fn A() {
   B() //error B not declared
}

fn B() {
}

```
This doesn' t compile because B isn't declared when defining A.

In that case, the issue could be solved by changing the ordering of the functions but the negative consequence is 
that the order of definitions becomes forced and ordering declarations based on importance more difficult.

The main issue, implemntation-wise, will be auto return types.
My understanding is that such a change would require declarations to be pre-parsed, same as in C++ currently when parsing class definitions
For instance, this works in C++:
```c++
class test
{
    void A() {
        B();
    }

    void B() {}
};
```

And also this:
```c++
class test
{
    auto A() {
        return B();
    }

    int B() { return 42; }
};

```

**Comment by jonmeow** [comment] 2022-07-26 15:51
Duplicate of #1416

**Closed as not planned by jonmeow** 2022-07-26 15:51 UTC
