### ISSUE TITLE
Reconsider name of `let` keyword

### ISSUE THREAD

**Issue by WarEagle451** [carbon-language/carbon-lang#1715] opened 2022-07-25 21:29 UTC
I suggest renaming `let` to `ref`.

Rational:
- At first glance the difference between `let` and `var` is not clear, as other languages use let to declare a variable (I'm looking at you JavaScript), IMO a keyword `ref` is more clear that `let`.
- According to the [design docs](https://github.com/carbon-language/carbon-lang/tree/trunk/docs/design#patterns), the binding pattern for `let` is supposed to be an equivalent to C++'s `const reference`.
- `ref` would maintain a nice alignment as `let` does with `var` for declarations.
- In #1578 `let` has already created confusion, and that it should be replaced with `const`.
- By default, the binding pattern for function params is `let`, which as stated before is supposed to be an equivalent to C++'s `const reference`, therefore in Carbon a pointer is what most expect from C++, while a `ref` would replace the need for a `const pointer` and would be the exact same as C++'s `const reference` (because pointers can't be null in Carbon).
- The above point mentioned a `const pointer`, [here](https://github.com/carbon-language/carbon-lang/tree/trunk/docs/design#const) in the design docs a `const pointer` is declared as `let p: const Point* = &origin;`, IMO `ref p: Point* = &origin;` reads a little bit cleaner.

Additionally I would like to see feed back on the name of `let` and my idea addressed separately. While I think I understand how `let` works fully now, there is confusion in #1578. I would like to know if more people are a little confused on `let` vs `const` and `let` vs `var`

**Comment by ElotonSotilas** [comment] 2022-07-25 23:56
To be honest, I'd rather just type the variable type instead of just `let`. I am having a feeling this language will turn into a low-key Rust clone and nobody will use it because of the learning barriers. I love having traits and such, but please, don't make this language like Rust. I already hate Rust as it stands.

**Comment by jonmeow** [comment] 2022-07-26 00:03
Duplicate of #1578

**Closed as not planned by jonmeow** 2022-07-26 00:03 UTC
