### ISSUE TITLE
question about code style

### ISSUE THREAD

**Issue by clime** [carbon-language/carbon-lang#1828] opened 2022-07-29 18:30 UTC
Hello,

this is just a suggestion. Would it be possible to switch to underscores, i.e. snake case, and start functions with a lower case letter?

Probably, the main reason is that it will make it easier to rewrite Python code into Carbon code (maybe one day in the future), which would be awesome (python for fast prototyping -> Carbon for production).

Even if this translation can be automated, it would be useful if the code looked more similar cause you then can easily navigate yourself once you worked with a prototype for some time.

**Comment by geoffromer** [comment] 2022-07-29 20:08
Duplicate of #1435

**Closed as not planned by geoffromer** 2022-07-29 20:08 UTC
