### ISSUE TITLE
Print does not allow to insert several variables in eventual std out

### ISSUE THREAD

**Issue by felix-seifert** [carbon-language/carbon-lang#2316] opened 2022-10-19 15:13 UTC
### Description of the bug:

If you want to include several variables in your print, an error appears that more than two arguments are not allowed for the `Print()` method.

### What did you do, or what's a simple way to reproduce the bug?

```
Print("Printing {0} and {1}", 20, 30);
```

### What did you expect to happen?

Expected output:
```
Printing 20 and 30
```

### What actually happened?

Received error:
```
COMPILATION ERROR: ./i32.carbon:14: Print takes 1 or 2 arguments, received 3
```

**Comment by jonmeow** [comment] 2022-10-19 16:41
Duplicate of #1801

**Closed as not planned by jonmeow** 2022-10-19 16:41 UTC
Labels: explorer
