### ISSUE TITLE
`new_proposal.py` permission error while PR adding reviewers

### ISSUE THREAD

**Issue by Pixep** [carbon-language/carbon-lang#1886] opened 2022-08-03 03:53 UTC
Running the new proposal script throws a permission error when trying to add reviewers for the PR.
That's easy enough to hack around, but will block anyone external to the repo.

The specific `gh` CLI argument:
```
        "--reviewer",
        "carbon-language/carbon-leads",
```

The best option is probably to default to no reviewer if permission level not sufficient, after testing with `gh`, or just checking for `gh pr` failure.

**Comment by emillaine** [comment] 2022-08-03 14:26
Seems to be duplicate of https://github.com/carbon-language/carbon-lang/issues/1841

**Comment by geoffromer** [comment] 2022-08-03 18:44
Closing as a duplicate of #1841.

**Comment by jonmeow** [comment] 2022-08-03 20:32
Duplicate of #1841

**Closed as not planned by jonmeow** 2022-08-03 20:32 UTC
