### ISSUE TITLE
Comparison operators don't work properly

### ISSUE THREAD

**Issue by y3v4psypl** [carbon-language/carbon-lang#1667] opened 2022-07-24 21:28 UTC
I've tried to write a simple program with Carbon

```
package Comparison api;

fn Main() -> i32 {

    var firstNum: i32 = 1;
    var secondNum: i32 = 2;
    
	if (firstNum > secondNum) {
		Print("1 is bigger than 2\n");
		return 0;
        }

	return 1;
}

```

and got stuck with an error:

```
COMPILATION ERROR: [PATH_TO_FILE]:8: invalid character '\x3E' in source file.
```

**Comment by jonmeow** [comment] 2022-07-24 21:58
Duplicate of #1549

**Closed as not planned** 2022-07-24 21:58 UTC
