### ISSUE TITLE
Please reconsider the syntax of initialisation in declaration and borrow from C++ the uniform initialization syntax

### ISSUE THREAD

**Issue by FLegendre** [carbon-language/carbon-lang#1917] opened 2022-08-04 13:36 UTC
Thank you very much for this initiative.

As it is important to distinguish between assignment and initialization, it seems to me that the proposed syntax (with the use of the = character) for initialization in the declaration is a bit confusing.

The C++11 solution to allow {}-initializer lists for all initialization is now a common practice.

With a text editor, it is easy to copy and paste the initializer expression.

It is also easier to spot assignments in the program if you specialise the = character for the assignment.

Can you also consider the ellision of braces when there is no ambiguity ?

**Comment by jonmeow** [comment] 2022-08-04 16:53
Duplicate of #1479

**Comment by jonmeow** [comment] 2022-08-04 16:54
If you have comments you would like to add to the other issue, please do so there: in this case, there is already the open question to leads about this feature, so it's best to centralize discussion.

**Closed as not planned by jonmeow** 2022-08-04 16:53 UTC
