### ISSUE TITLE
FATAL failure at explorer/syntax/prelude.cpp:22

### ISSUE THREAD

**Issue by enstazao** [carbon-language/carbon-lang#3539] opened 2023-12-23 15:45 UTC
### Description of the bug:

> 3d)
 #1 0x000055dc9e69b93b PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #2 0x000055dc9e698a36 llvm::sys::RunSignalHandlers() (/home/jadi/.cache/bazel/_bazel_jadi/f4216e1626b285d717746469bddba6b1/execroot/_main/bazel-out/k8-fastbuild/bin/explorer/explorer+0x87ba36)
 #3 0x000055dc9e69c675 SignalHandler(int) Signals.cpp:0:0
 #4 0x00007f8875a42520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #5 0x00007f8875a969fc __pthread_kill_implementation ./nptl/pthread_kill.c:44:76
 #6 0x00007f8875a969fc __pthread_kill_internal ./nptl/pthread_kill.c:78:10
 #7 0x00007f8875a969fc pthread_kill ./nptl/pthread_kill.c:89:10
 #8 0x00007f8875a42476 gsignal ./signal/../sysdeps/posix/raise.c:27:6
 #9 0x00007f8875a287f3 abort ./stdlib/abort.c:81:7
#10 0x000055dc9e60dc35 (/home/jadi/.cache/bazel/_bazel_jadi/f4216e1626b285d717746469bddba6b1/execroot/_main/bazel-out/k8-fastbuild/bin/explorer/explorer+0x7f0c35)
#11 0x000055dc9e1b73c5 (/home/jadi/.cache/bazel/_bazel_jadi/f4216e1626b285d717746469bddba6b1/execroot/_main/bazel-out/k8-fastbuild/bin/explorer/explorer+0x39a3c5)
#12 0x000055dc9e52caa9 Carbon::AddPrelude(llvm::vfs::FileSystem&, std::__1::basic_string_view<char, std::__1::char_traits<char>>, Carbon::Arena*, std::__1::vector<Carbon::Declaration*, std::__1::allocator<Carbon::Declaration*>>*, int*) (/home/jadi/.cache/bazel/_bazel_jadi/f4216e1626b285d717746469bddba6b1/execroot/_main/bazel-out/k8-fastbuild/bin/explorer/explorer+0x70faa9)
#13 0x000055dc9e1cf030 Carbon::ParseAndExecute(llvm::vfs::FileSystem&, std::__1::basic_string_view<char, std::__1::char_traits<char>>, std::__1::basic_string_view<char, std::__1::char_traits<char>>, bool, Carbon::TraceStream*, llvm::raw_ostream*)::$_0::operator()() const parse_and_execute.cpp:0:0
#14 0x000055dc9e1cf6f5 decltype(fp()) Carbon::RunWithExtraStack<Carbon::ParseAndExecute(llvm::vfs::FileSystem&, std::__1::basic_string_view<char, std::__1::char_traits<char>>, std::__1::basic_string_view<char, std::__1::char_traits<char>>, bool, Carbon::TraceStream*, llvm::raw_ostream*)::$_0>(Carbon::ParseAndExecute(llvm::vfs::FileSystem&, std::__1::basic_string_view<char, std::__1::char_traits<char>>, std::__1::basic_string_view<char, std::__1::char_traits<char>>, bool, Carbon::TraceStream*, llvm::raw_ostream*)::$_0)::'lambda'()::operator()() const parse_and_execute.cpp:0:0
#15 0x000055dc9e1cf6c5 void llvm::function_ref<void ()>::callback_fn<decltype(fp()) Carbon::RunWithExtraStack<Carbon::ParseAndExecute(llvm::vfs::FileSystem&, std::__1::basic_string_view<char, std::__1::char_traits<char>>, std::__1::basic_string_view<char, std::__1::char_traits<char>>, bool, Carbon::TraceStream*, llvm::raw_ostream*)::$_0>(Carbon::ParseAndExecute(llvm::vfs::FileSystem&, std::__1::basic_string_view<char, std::__1::char_traits<char>>, std::__1::basic_string_view<char, std::__1::char_traits<char>>, bool, Carbon::TraceStream*, llvm::raw_ostream*)::$_0)::'lambda'()>(long) parse_and_execute.cpp:0:0
#16 0x000055dc9e52c8b9 llvm::function_ref<void ()>::operator()() const (/home/jadi/.cache/bazel/_bazel_jadi/f4216e1626b285d717746469bddba6b1/execroot/_main/bazel-out/k8-fastbuild/bin/explorer/explorer+0x70f8b9)
#17 0x000055dc9e52c896 Carbon::Internal::RunWithExtraStackHelper(llvm::function_ref<void ()>)::$_0::operator()() const stack_space.cpp:0:0
#18 0x000055dc9e52c845 void llvm::function_ref<void ()>::callback_fn<Carbon::Internal::RunWithExtraStackHelper(llvm::function_ref<void ()>)::$_0>(long) stack_space.cpp:0:0
#19 0x000055dc9e52c8b9 llvm::function_ref<void ()>::operator()() const (/home/jadi/.cache/bazel/_bazel_jadi/f4216e1626b285d717746469bddba6b1/execroot/_main/bazel-out/k8-fastbuild/bin/explorer/explorer+0x70f8b9)
#20 0x000055dc9e659f2a llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/home/jadi/.cache/bazel/_bazel_jadi/f4216e1626b285d717746469bddba6b1/execroot/_main/bazel-out/k8-fastbuild/bin/explorer/explorer+0x83cf2a)
#21 0x000055dc9e65a3bf RunSafelyOnThread_Dispatch(void*) CrashRecoveryContext.cpp:0:0
#22 0x000055dc9e65aae4 auto void llvm::thread::GenericThreadProxy<std::__1::tuple<void (*)(void*), (anonymous namespace)::RunSafelyOnThreadInfo*>>(void*)::'lambda'(auto&&, auto&&...)::operator()<void (*&)(void*), (anonymous namespace)::RunSafelyOnThreadInfo*&>(auto&&, auto&&...) const CrashRecoveryContext.cpp:0:0
#23 0x000055dc9e65aa75 decltype(std::declval<auto>()(std::declval<auto>()...)) std::__1::__invoke[abi:he170006]<void llvm::thread::GenericThreadProxy<std::__1::tuple<void (*)(void*), (anonymous namespace)::RunSafelyOnThreadInfo*>>(void*)::'lambda'(auto&&, auto&&...), void (*&)(void*), (anonymous namespace)::RunSafelyOnThreadInfo*&>(auto&&, auto&&...) CrashRecoveryContext.cpp:0:0
#24 0x000055dc9e65aa3e decltype(auto) std::__1::__apply_tuple_impl[abi:he170006]<void llvm::thread::GenericThreadProxy<std::__1::tuple<void (*)(void*), (anonymous namespace)::RunSafelyOnThreadInfo*>>(void*)::'lambda'(auto&&, auto&&...), std::__1::tuple<void (*)(void*), (anonymous namespace)::RunSafelyOnThreadInfo*>&, 0ul, 1ul>(auto&&, std::__1::tuple<void (*)(void*), (anonymous namespace)::RunSafelyOnThreadInfo*>&, std::__1::__tuple_indices<0ul, 1ul>) CrashRecoveryContext.cpp:0:0
#25 0x000055dc9e65a9cd decltype(auto) std::__1::apply[abi:he170006]<void llvm::thread::GenericThreadProxy<std::__1::tuple<void (*)(void*), (anonymous namespace)::RunSafelyOnThreadInfo*>>(void*)::'lambda'(auto&&, auto&&...), std::__1::tuple<void (*)(void*), (anonymous namespace)::RunSafelyOnThreadInfo*>&>(auto&&, std::__1::tuple<void (*)(void*), (anonymous namespace)::RunSafelyOnThreadInfo*>&) CrashRecoveryContext.cpp:0:0
#26 0x000055dc9e65a97c void llvm::thread::GenericThreadProxy<std::__1::tuple<void (*)(void*), (anonymous namespace)::RunSafelyOnThreadInfo*>>(void*) CrashRecoveryContext.cpp:0:0
#27 0x000055dc9e65a7c5 void* llvm::thread::ThreadProxy<std::__1::tuple<void (*)(void*), (anonymous namespace)::RunSafelyOnThreadInfo*>>(void*) CrashRecoveryContext.cpp:0:0
#28 0x00007f8875a94ac3 start_thread ./nptl/pthread_create.c:442:8
#29 0x00007f8875b26660 ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:83:0
FATAL failure at explorer/syntax/prelude.cpp:22: Failed to parse prelude:
prelude.carbon:0: Error opening file: No such file or directory

**Comment by ArmDaniel** [comment] 2023-12-23 20:15
Can you kindly provide the steps in order to reproduce this error?

**Comment by chandlerc** [comment] 2023-12-24 20:19
This is an issue in the explorer, and we've de-prioritized fixes here to focus all of our energy on the toolchain:
https://github.com/carbon-language/carbon-lang/blob/trunk/proposals/p3532.md

We've tried to fix all of the documentation to reflect this change, but if we missed anything let us know (likely in a separate issue or on Discord) and we'll update there as well. Closing the issue for now.

**Closed as not planned by chandlerc** 2023-12-24 20:19 UTC
Labels: explorer

**Comment by jonmeow** [comment] 2024-01-02 18:54
@chandlerc You closed this as "not planned", but it looks like a duplicate of #3541. Note, that issue was fixed by #3544.
