### ISSUE TITLE
Compiler is Always Expecting Type String , when we have Integers to print, Leading to Compilation Errors

### ISSUE THREAD

**Issue by akashakash24** [carbon-language/carbon-lang#2337] opened 2022-10-24 07:21 UTC
### Description of the bug:

While Trying to print the sum of Two i32 variables, The compiler throws an error saying expected type is String.

COMPILATION ERROR: <source>:6: type error in Print argument 0
expected: String
actual: i32
Compiler returned: 1

### What did you do, or what's a simple way to reproduce the bug?

https://godbolt.org/z/bsd16K7vE

### What did you expect to happen?

The expected output is 1+2 = 3.
The Output should be displayed.

### What actually happened?

Compilation Error

### Any other information, logs, or outputs that you want to share?

![image](https://user-images.githubusercontent.com/31944412/197469715-525334ca-f853-4bc0-b61d-09ec08b9031a.png)

**Comment by akashakash24** [comment] 2022-10-24 07:35
Can we add provision to display integers in the same format as string, instead of  Print("{0}  ", x);

**Comment by jonmeow** [comment] 2022-10-24 15:42
Print is only implemented enough for debugging tooling right now.

Duplicate of #1801

**Closed as not planned by jonmeow** 2022-10-24 15:42 UTC
Labels: explorer
