### ISSUE TITLE
Enabling `auto` for global variables

### ISSUE THREAD

**Issue by i-Sa3ed** [carbon-language/carbon-lang#2634] opened 2023-02-26 06:39 UTC
### Description of the bug:

if you tried this line of code globally (outside any function)
`var y: auto = 13;`
it will produce this error: "Expected expression for variable type"

### What did you expect to happen?

the goal is to make this line acceptable by Carbon Explorer

**Comment by Axyte** [comment] 2023-02-26 16:47
Can't reproduce [here](https://carbon.compiler-explorer.com/z/K5P8zv94r).

**Comment by jatinsahijwani** [comment] 2023-02-27 05:13
i want to work on this issue, please assign it to me

**Comment by Aditya9764** [comment] 2023-02-27 05:28
i want  to contribute in your organization under the project at GSOC 2023 "Improve the user facing carbon output  " can you please tell where to contact because their is no such email or mentor name 

Please reply

**Comment by i-Sa3ed** [comment] 2023-02-27 06:32
> i want to work on this issue, please assign it to me

ok, if you need any help please reach out one of the moderators on Discord, like Mr @Pixep 
Edit: I think assigning need an access that I don't have, just start working and @Pixep or any another moderator will do that

**Comment by i-Sa3ed** [comment] 2023-02-27 06:33
> i want to contribute in your organization under the project at GSOC 2023 "Improve the user facing carbon output " can you please tell where to contact because their is no such email or mentor name
> 
> Please reply

You can find the discord server in "README" file of this repo, feel free to enter and ask and start contribution..

**Comment by jonmeow** [comment] 2023-02-27 17:09
This is a duplicate of #1093, so I'm closing this issue. Please follow up on this issue there.

@Aditya9764  Regarding gsoc, this issue isn't the right place to discuss that program. You can ask questions on [Discord](https://discord.gg/ZjVdShJDAs) (there's a #gsoc channel there), or if you don't want to ask on Discord, use [GitHub discussions](https://github.com/carbon-language/carbon-lang/discussions).

**Closed as not planned by jonmeow** 2023-02-27 17:09 UTC
Labels: explorer

**Comment by i-Sa3ed** [comment] 2023-02-28 12:45
> This is a duplicate of #1093, so I'm closing this issue. Please follow up on this issue there.
> 
> @Aditya9764 Regarding gsoc, this issue isn't the right place to discuss that program. You can ask questions on [Discord](https://discord.gg/ZjVdShJDAs) (there's a #gsoc channel there), or if you don't want to ask on Discord, use [GitHub discussions](https://github.com/carbon-language/carbon-lang/discussions).

I'm sorry, I didn't notice that there's already open issue for the same bug :)
