### ISSUE TITLE
[Question] Website

### ISSUE THREAD

**Issue by joaodematejr** [carbon-language/carbon-lang#1579] opened 2022-07-22 20:47 UTC
Is there any provision for creating a website, I am willing to help. 

https://docusaurus.io/docs

**Comment by davidzchen** [comment] 2022-07-22 20:56
Great!

There is an ongoing discussion on the website in #1492.

**Comment by jonmeow** [comment] 2022-07-22 21:06
Duplicate of #1492

**Closed as completed** 2022-07-22 21:06 UTC
