### ISSUE TITLE
Make sure the string literals are JSON-friendly

### ISSUE THREAD

**Issue by Hermholtz** [carbon-language/carbon-lang#1864] opened 2022-08-01 09:24 UTC
Hi,

I didn't see it mentioned clearly that currently proposed string literals allow for easy handling of ubiquitous JSON data (that is - that JSON data in the form of a string literal doesn't need any escaping). It should also be friendly to formatting. I mean it should be possible to do the following (I've made up the syntax, don't know if the current one supports this):

```
var str: String = """
{
    root: { propertyName: "value1" }
}
""";
```

but also the following:

```
var value_to_insert: String = "value1";

var str: String = ff"""
{
    root: { propertyName: "{{value_to_insert}}" }
}
""";
```

and even this:

```
var value_to_insert: String = "value1";

var str: String = fff"""
{
    root: { propertyName: "{{{value_to_insert}}}" }
}
""";
```

so that nesting is possible (e.g. in the multi-line strings require the same amount of curly braces as "f"s for the interpolation to work).
It will help also with XML, SQL and Regex strings.
I suggest that it is considered on early stages of language design.

Thanks.

**Comment by jonmeow** [comment] 2022-08-01 15:07
The first example is [already valid syntax](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/design/lexical_conventions/string_literals.md#simple-and-block-string-literals). The rest seems to be a comment about how interpolation should work. Interpolation isn't supported today; I would consider this a duplicate of the issue suggesting them.

Duplicate of #1811

**Closed as not planned by jonmeow** 2022-08-01 15:07 UTC

**Comment by Hermholtz** [comment] 2022-08-01 15:12
Feel free to mark this as a duplicate, just note that this interpolation proposal is much more flexible than the one you referenced.

**Comment by jonmeow** [comment] 2022-08-01 16:23
In marking this a duplicate, I mainly mean "this feature is already under consideration", not "the described approach is identical". Your comment would be better as a response to the other issue, in order to allow discussion without expecting involved people to search for related issues.

As [chandlerc says](https://github.com/carbon-language/carbon-lang/issues/1811#issuecomment-1200071863), the current issue is the lack of a proposal. The [evolution process](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/evolution.md) doc describes how to do this if you're interested. To be clear, we use PRs for making decisions on proposals, issues are primarily used for leads (chandlerc, zygoloid, and KateGregory) to give feedback on direction, avoiding spending time on ideas they're unlikely to accept.

**Comment by Hermholtz** [comment] 2022-08-01 19:17
Thanks for detailed answer. I'm not that very proficient in language design or governance, nor have enough spare time to write a full proposal, hence just tried to make you aware of a potential important requirement from users of your language. Flexible string formatting and interpolation is really a must have. 

And by the way please when designing features do not invent awkwardness like [the horrible way of custom date/datetime formatting in Go](https://pkg.go.dev/time#Time.String). It's beyond my comprehension why they've done it (apparently knowing the YYYY-MM-DD stuff).

Good luck!

**Comment by jonmeow** [comment] 2022-08-01 21:16
@Hermholtz Please avoid calling other languages "horrible" here -- thanks!
