### ISSUE TITLE
Replace let with const

### ISSUE THREAD

**Issue by psychobug420** [carbon-language/carbon-lang#2167] opened 2022-09-12 08:59 UTC
```
package Sorting api;

fn Partition[T:! Comparable & Movable](s: Slice(T))
     -> i64 {
  var i: i64 = -1;

  for (e: T in s) {
    if (e <= s.Last()) {
      ++i;
      Swap(&s[i], &e);
    }
  }
  return i;
}

fn QuickSort[T:! Comparable & Movable](s: Slice(T)) {
  if (s.Size() <= 1) {
    return;
  }
  let p: i64 = Partition(s);
  QuickSort(s[:p - 1]);
  QuickSort(s[p + 1:]);
}
```

What is the differrence here between **var** and **let**?
Is it about constant variables or just misstype, if one of them about constant i'd better suggest use **var** or **let** for non constant and **const** for constant variables, as done in JavaScript or use some modifiers with **var** or **let** like **const var** or **const let**

**Comment by danielkrash** [comment] 2022-09-12 10:03
https://github.com/carbon-language/carbon-lang/tree/trunk/docs/design#constant-let-declarations

**Comment by psychobug420** [comment] 2022-09-12 14:09
I don't know does it fits in this language, but maybe **const** keyword would fit better and make language more intuitive, to make it easier to learn and bring more newcomers, it's a little feature but the language builds from little features and it's beautifulness is build by them, if there are several reasons not to use **const** keyword, than this issue can be closed
I think that such changes are possible when language is experimental and not in production🙃

**Comment by ghost** [comment] 2022-09-12 14:59
> https://github.com/carbon-language/carbon-lang/tree/trunk/docs/design#constant-let-declarations

let is an irrefutable pattern. As in "let it be so". Design specifications have thusfar led to an inerpreter. The next understanding of the use of the keyword let may come if we explore why is let a pattern. Appears there is a joined purpose already designed into let. The interpreter can possiby interpret patterns in one large batch, including irrefutable patterns, and all let keyords. I don't know myself either. Simply guiding this issue to the design specifications.

Irrefutable patterns are guaranteed to match, so long as the code type-checks.

**Comment by jonmeow** [comment] 2022-09-12 17:17
Duplicate of #1578

**Closed as not planned by jonmeow** 2022-09-12 17:17 UTC

**Comment by jonmeow** [comment] 2022-09-12 17:18
(note, I'm interpreting this as identical to the request to change the keyword name, but above comments that C++'s `const` and Carbon's `let` are different are correct)
