### ISSUE TITLE
Need a official website for the carbon language...

### ISSUE THREAD

**Issue by ItsRoy69** [carbon-language/carbon-lang#1649] opened 2022-07-24 14:59 UTC

**Comment by pacion** [comment] 2022-07-24 16:06
Yeah +1.
Admins what do you think about creating new repository which is also open source? (need to publish docs somewhere)

**Comment by jonmeow** [comment] 2022-07-24 16:20
> Admins what do you think about creating new repository which is also open source? (need to publish docs somewhere)

The intent is to keep as much as we can in `carbon-lang`

**Comment by jonmeow** [comment] 2022-07-24 16:21
Duplicate of #1492

**Comment by robiot** [comment] 2022-07-25 07:01
> Duplicate of #1492 

Maybe close this to keep the open issues clear from duplicates?

**Comment by jonmeow** [comment] 2022-07-25 17:42
@robiot Missed the button, thanks for pointing that out. :)

**Closed as not planned** 2022-07-25 17:41 UTC
