### ISSUE TITLE
Carbon Explorer Fails with Error CHECK in NumPossibleCPUsNoCache: cpus.has_value() (false) 

### ISSUE THREAD

**Issue by axsaucedo** [carbon-language/carbon-lang#4176] opened 2024-07-28 06:28 UTC
# Description of the bug:

Carbon Explorer fails with error `NumPossibleCPUsNoCache: cpus.has_value() (false)`

# Full error:

```
1 external/tcmalloc~/tcmalloc/internal/sysinfo.cc:124] CHECK in NumPossibleCPUsNoCache: cpus.has_value() (false) 
Program terminated with signal: SIGSEGV
Compiler returned: 139
```

# Screenshot

<img width="1339" alt="image" src="https://github.com/user-attachments/assets/39ba37b8-42d7-47a7-a9d8-4e5aa78bec7a">

### What did you do, or what's a simple way to reproduce the bug?

Opened the default example in Chrome / Firefox and error appeared.

### What did you expect to happen?

Default examples should work.

### What actually happened?

Errors above.

**Comment by jonmeow** [comment] 2024-07-29 15:14
@chandlerc It looks like this is just tcmalloc not handling compiler-explorer's environment. I expect having that work is more important than having tcmalloc, so I'll send you a rollback.

**Comment by jonmeow** [comment] 2024-07-29 15:25
Thanks for reporting this, I've sent out a change to disable it. Note it'll probably be a day for compiler-explorer to pick up a new build.

**Comment by jonmeow** [comment] 2024-07-29 15:51
Filed https://github.com/google/tcmalloc/issues/245 regarding this

**Comment by jonmeow** [comment] 2024-07-29 21:51
tcmalloc is probably going to keep the behavior. Following up with compiler-explorer to see about whitelisting the /sys file now: https://github.com/compiler-explorer/compiler-explorer/issues/6734

**Comment by jonmeow** [comment] 2024-07-29 21:53
Note, this also follows some discussion with @zygoloid that even though glibc has a fallback for this situation, we will probably only support linux versions that have the /sys file.

**Comment by axsaucedo** [comment] 2024-08-03 10:17
Thank you for the prompt reply and context @jonmeow - it seems the carbon explorer is working for the time being with the workaround

**Comment by chandlerc** [comment] 2024-08-03 21:49
Root cause should be fixed in Compiler Explorer now: https://github.com/compiler-explorer/compiler-explorer/issues/6734

Sent a PR to re-enable TCMalloc and once it's live and not crashing, should be able to resolve this fully.

**Closed as completed** 2024-08-05 14:36 UTC
Labels: explorer
